//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the DC (alias tactac kiki 🤣) Templates so
//  you can use now the benj architecture to Amex GBT project,
//  see https://gitlab.kdsneo.kds.com/blorenzi/iosarchitecture/tree/master/IOSArchitecture/Tutorial
//

import UIKit


class ___VARIABLE_featureName___ViewController: UIViewCoordinable, FeatureViewController {
    typealias ViewModel = ___VARIABLE_featureName___ViewModel
    var viewModel: ___VARIABLE_featureName___ViewModel?
    
    typealias Actions = ___VARIABLE_featureName___ActionProtocol
    var actions: ___VARIABLE_featureName___ActionProtocol?
    
    // TODO 2) @IBOutlet declaration
    //@IBOutlet weak var username: UILabel!
    //var username = UILabel()
    //var biomeTryLabel = UILabel()
    //var logOut = UIButton()
    
    // MARK: View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        // navigationItem.title = "Account"
        // username.accessibilityIdentifier = "usernameLabel"
        //buildUI()
        updateUI()
    }
    
     // TODO 3) Build UI
    /*
    func buildUI() {
        // TODO: Build UI
        navigationItem.title = "Account"
        username.accessibilityIdentifier = "usernameLabel"
        
        view.addSubview(username)
        view.addSubview(biomeTryLabel)
        view.addSubview(logOut)
        view.backgroundColor = UIColor.white
        
        biomeTryLabel.textColor = UIColor.black
        biomeTryLabel.frame = CGRect(x: 150, y:150, width: 250, height: 40)
        biomeTryLabel.text = "none"
     
        username.textColor = UIColor.black
        username.frame = CGRect(x: 150, y:100, width: 250, height: 40)
        username.text = "Welcome Bob"
     
        logOut.backgroundColor = UIColor.blue
        logOut.setTitleColor(UIColor.blue, for: .normal)
        logOut.frame = CGRect(x: 100, y:400, width: 250, height: 50)
        
        logOut.setTitle("LogOut", for: .normal)
        logOut.titleLabel?.numberOfLines = 0
        logOut.layer.cornerRadius = 5
        logOut.setTitleColor(.white, for: .normal)
        logOut.addTarget(self, action: #selector(didClickOnButton(sender:)), for: .touchUpInside)
        
    }*/
    
    // MARK: Update logic
    // TODO 10) 
    func updateUI(viewModel: ___VARIABLE_featureName___ViewModel) {
        //username.text = "Welcome \(viewModel.username)"
        //biomeTryLabel.text = viewModel.supportedBiometry.localizedValue
    }

    // TODO 4) -> Break Fix 
    // MARK: Interaction Logic
    // define here some @IBAction or some interaction between
    // the app and the user
    //
    // see example below
    //
    /*
    @objc func didClickOnButton(sender: Any?) {
        actions?.logOut()
    }*/
}
