//
//  AccountViewController.swift
//  IOSArchitecture
//
//  Created by Benjamin LORENZI on 11/03/2020.
//  Copyright (c) 2020 Benjamin LORENZI. All rights reserved.
//
//  This file was generated by the DC (alias tactac kiki 🤣) Templates so
//  you can use now the benj architecture to Amex GBT project,
//  see https://gitlab.kdsneo.kds.com/blorenzi/iosarchitecture/tree/master/IOSArchitecture/Tutorial
//

import UIKit


class AccountViewController: UIViewCoordinable, FeatureViewController {
    typealias ViewModel = AccountViewModel
    var viewModel: AccountViewModel?
    
    typealias Actions = AccountActionProtocol
    var actions: AccountActionProtocol?
    
    // TODO 2) @IBOutlet declaration
    //@IBOutlet weak var username: UILabel!
    var username = UILabel()
    var biomeTryLabel = UILabel()
    var logOut = UIButton()
    
    // MARK: View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        // navigationItem.title = "Account"
        // username.accessibilityIdentifier = "usernameLabel"
        buildUI()
        updateUI()
    }
    
     // TODO 3) Build UI
    func buildUI() {
        // TODO: Build UI
        navigationItem.title = "Account"
        username.accessibilityIdentifier = "usernameLabel"
        
        view.addSubview(username)
        view.addSubview(biomeTryLabel)
        view.addSubview(logOut)
        view.backgroundColor = UIColor.white
        
        biomeTryLabel.textColor = UIColor.black
        biomeTryLabel.frame = CGRect(x: 150, y:150, width: 250, height: 40)
        biomeTryLabel.text = "none"
     
        username.textColor = UIColor.black
        username.frame = CGRect(x: 150, y:100, width: 250, height: 40)
        username.text = "Welcome Bob"
     
        logOut.backgroundColor = UIColor.blue
        logOut.setTitleColor(UIColor.blue, for: .normal)
        logOut.frame = CGRect(x: 100, y:400, width: 250, height: 50)
        
        logOut.setTitle("LogOut", for: .normal)
        logOut.titleLabel?.numberOfLines = 0
        logOut.layer.cornerRadius = 5
        logOut.setTitleColor(.white, for: .normal)
        logOut.addTarget(self, action: #selector(didClickOnButton(sender:)), for: .touchUpInside)
        
    }
    
    // MARK: Update logic
    // TODO 10) 
    func updateUI(viewModel: AccountViewModel) {
        username.text = "Welcome \(viewModel.username)"
        biomeTryLabel.text = viewModel.biometryStatus
    }

    // TODO 4) -> Break Fix 
    // MARK: Interaction Logic
    // define here some @IBAction or some interaction between
    // the app and the user
    //
    // see example below
    //
    @objc func didClickOnButton(sender: Any?) {
        actions?.logOut()
    }
}
